[package]
name = "book-handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
book-usecase = { path = "../../book-usecase" }
actix-web = "4.2.1"
